### ISSUE TITLE
No support for /capacity API

### ISSUE THREAD

**Issue by rushiagr** [packethost/packet-python#17]
Capacity ReST API:
https://www.packet.net/help/api/#page:capacity,header:capacity-capacity

It'd be great to add support for capacity, as just for this function I am making a direct API call right now.

**Comment by crunchywelch** [comment]
there are currently some issues with the capacity endpoint, so I'm going to ack this but not proceed on it for now...

**Comment by mmlb** [comment]
This was added in 20b50934544fa28801fabdee0d04be40ca9e9cbd
