### ISSUE TITLE
Cloning Volumes

### ISSUE THREAD

**Issue by DannyAziz** [packethost/packet-python#21]
I realized that you couldn't clone volumes, so I forked the project and implemented it myself. 

Not sure how to actually contribute, but here you go if anybody wants it: https://github.com/DannyAziz/packet-python

**Comment by jacobsmith928** [comment]
Hey thanks @DannyAziz I'll let @crunchywelch handle this!

**Comment by crunchywelch** [comment]
added, will include in next release, thanks @DannyAziz
