### ISSUE TITLE
status -> state

### ISSUE THREAD

**Issue by johnstudarus** [packethost/packet-python#43]
The "Checking the status and rebooting a Device" example on the PyPi document page references 'Status' however, the correct attribute is 'State'.

import packet
manager = packet.Manager(auth_token="yourapiauthtoken")

device = manager.get_device('device-id')
print(device.status)                         <----- should be device.state
device.reboot()

**Comment by mmlb** [comment]
Re-opening since this mentions pypi, will be pushing an update soon.

**Comment by mmlb** [comment]
Now up on pypi in v1.38.1, :toot:

**Comment by johnstudarus** [comment]
Thanks!
