### ISSUE TITLE
java client

### ISSUE THREAD

**Issue by unicomp21** [packethost/packet-python#5]
Where is the java client?

**Comment by crunchywelch** [comment]
hi @unicomp21 we don't have a pure java client on our roadmap currently, so far no one has asked about it. Do you have a use case for it? We can certainly add it to the roadmap if there is a compelling reason and need for one!

**Comment by unicomp21** [comment]
DigitalOcean has one.

**Comment by crunchywelch** [comment]
is this the one you are referring to?

https://github.com/jeevatkm/digitalocean-api-java

If it had feature parity with that, would that work?

**Comment by unicomp21** [comment]
Yep, that would do the trick.

**Comment by crunchywelch** [comment]
sounds good, I made a repo here:

https://github.com/packethost/packet-java

Will close this now and see about working it into our roadmap...

Cheers!

**Comment by unicomp21** [comment]
Thx!
