### ISSUE TITLE
create_ssh_key returns 404

### ISSUE THREAD

**Issue by mattdavis0351** [packethost/packet-python#78]
## Problem
Using this method returns 404 even though the resource gets created as expected in the Packet Project.

**Method:**
```python
key = manager.create_ssh_key(label="matt-desktop,
                             public_key="some key")
```

**Error:**
```
packet\baseapi.py", line 92, in call_api
raise Error("Error {0}: {1}".format(resp.status_code, msg))
packet.baseapi.Error: Error 404: Not found
```
**Resource actually created:**
![image](https://user-images.githubusercontent.com/38021615/77992756-8e5bb300-72db-11ea-9bb3-198314cc15b7.png)

The key that is set for this label is the **correct public key** from my key file.  Therefore returning `404` makes no sense.  

This error also stops the rest of the execution for this script... as expected.

**Comment by mattdavis0351** [comment]
##Update

When using a Project Level API key the above error exists,

When using a Personal API key the above code works as expected.

**Comment by vielmetti** [comment]
Referenced in #80

**Comment by displague** [comment]
I was able to reproduce this problem in the latest master branch by using a project API key instead of a user API key.

I created this branch to attempt to prevent the redirect from happening after the 201 response is received, but I still received a 404.  

https://github.com/packethost/packet-python/compare/master...displague:disable-allow-redirects.patch

**Comment by displague** [comment]
This problem should now be resolved thanks to changes in the Equinix Metal (Packet) API.

We should be able to revert the work-around created here: 
https://github.com/packethost/packet-python/pull/80/files#diff-4b7536d3531098c5ab1cf269f404aa499c4effb6b3595203f88e6e16b218e9b5R201-R240

Feel free to re-open this, @mattdavis0351 if the problem persists.
