### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by invidian** [packethost/packet-python#79]
We got this stack trace today, while Packet API had some issues:
```
Deleting devices older than 60 minutes
Traceback (most recent call last):
  File "ci/task-scripts/delete-old-packet-devices", line 57, in <module>
    page = manager.list_devices(project_id=project_id,
  File "/usr/local/lib/python3.8/site-packages/packet/Manager.py", line 92, in list_devices
    data = self.call_api("projects/%s/devices" % project_id, params=params)
  File "/usr/local/lib/python3.8/site-packages/packet/Manager.py", line 30, in call_api
    return super(Manager, self).call_api(method, type, params)
  File "/usr/local/lib/python3.8/site-packages/packet/baseapi.py", line 90, in call_api
    elif "errors" in data:
TypeError: a bytes-like object is required, not 'str'
```

If I understand correctly, API returned string instead of JSON? and this was unhandled?

**Comment by vielmetti** [comment]
Hi @invidian - has this problem reappeared? We corrected some data that was erroneously being returned from the API for some system types.

**Comment by invidian** [comment]
No, it didn't reappear for us. I'm fine with closing the issue I guess, if you think code changes are not required here, to handle such unexpected cases better :)

**Comment by vielmetti** [comment]
Thanks @invidian - I'll happily keep this open as a note to flag the library for hardening in the case of unexpected API returns.

**Comment by vielmetti** [comment]
This duplicates #45 (when the API is down, the library behaves badly).

**Comment by vielmetti** [comment]
Closing in favor of #45 which has more details.
